# 2022_12_15_changes_in_clonal_frequency.R
# Diagnostic Visualizations AND Generated Inputs for Figure 4
# INPUTS:
# + 'control/2022_12_15_control_df_outerjoins.csv' (control file, spec comparisons)
# + 'tcrb/longitudinal/post2_pre/*_TCRB.tsv (generated by 2022_12_15_outer_join_timepoints_and_compute_FDR.py)
# + 'tcrb/longitudinal/post1_pre/*_TCRB.tsv (generated by 2022_12_15_outer_join_timepoints_and_compute_FDR.py)
# RETURNS:
# + 'diagnostic_figures/*.pdf'
# + 'data/tcrb/tcrb_matched_ics/summary_info_for_2x_fold_change_FDR_gt_0.05_expanded_clones.tsv'
# + 'data/tcrb/tcrb_matched_ics/expanded_clones_for_2x_fold_change_FDR_gt_0.05_expanded_clones.tsv'
# + +  Expanded clones must have changed 2x fold change and FDR < 0.05 based on fisher's exact test adjusted p-values.
# + + The above file is used in code/figure_4_expanded_clones.R

# NOTES:
# Dec 15, 2022 Code is re factored to use PUBID identifies
# Dec 2, 2021 - this was based on a critical script that makes expansion plots 
  # and outputs the summary information needed for making ICS vs clonal breadth 
  # comparisons.

# DEPENDENDENCES:
require(ggplot2)
require(dplyr)
base_dir = "/fh/fast/gilbert_p/fg_data/mcelrath_covid/mrna_cd8_tcell_project"
fold_change = 2
fdr_threshold = 0.05
setwd(base_dir)
df = readr::read_csv('control/2022_12_15_control_df_outerjoins.csv')
out_dir = 'data/tcrb_matched_ics'
out_fig_dir = 'diagnostic_figures'
Sys.setenv("DISPLAY"=":0.0")
files = df$filename
tags = df$tag
tags1 = stringr::str_extract(df$f1, pattern = "CO001-[0-9]{6}_v[0-9]{1,3}")
tags2 = stringr::str_extract(df$f2, pattern = "CO001-[0-9]{6}_v[0-9]{1,3}")

# <packrat> is a lsit to store results
packrat = list()
packrat_expanded_clones = list()
for (i in seq(1, length(files))){  
  dfx = readr::read_tsv(files[i]) 
  dfx = dfx %>% mutate(productive_frequency_y = ifelse(productive_frequency_y == 0, 0.000001, productive_frequency_y))
  dfx = dfx %>% mutate(productive_frequency_x = ifelse(productive_frequency_x == 0, 0.000001, productive_frequency_x))    
  
  # We wish to draw the users attention to particular point. 
  abr  = paste0(tags[i],"__",tags2[i],"__",tags1[i])
  filename =  paste0(tags[i],"__",tags2[i],"__",tags1[i], paste0("__basic_fdr_",fdr_threshold,"_with_",fold_change,"x_fold_change.pdf"))
  filepath = file.path(out_fig_dir, filename)
  print(filepath)
  
  # identify the expanders
  focus_greater = dfx %>% filter(post_pre_fdr_bh < fdr_threshold, productive_frequency_x > productive_frequency_y * fold_change)
  focus_less = dfx %>% filter(post_pre_fdr_bh < fdr_threshold, productive_frequency_y > productive_frequency_x * fold_change)
  
  # What is the breadth of expanded clones
  expanded_clones = focus_greater %>% group_by(rank_x) %>% slice(1) %>% ungroup()
  expanded_clones = expanded_clones %>% mutate(
    source_file = files[i], 
    fold_change = fold_change, 
    fdr_threshold = fdr_threshold,
    associated_pdf= filename, 
    type = tags[i],
    post = tags2[i],
    pre = tags1[i]) 
  
  summary_df = data.frame(
    breadth_expanded_clones = dim(expanded_clones)[1],
    sum_pf_expanded_clones = sum(expanded_clones$productive_frequency_x),
    sum_templates_expanded_clones = sum(expanded_clones$templates_x),
    simpson_expanded_clones = vegan::diversity(expanded_clones$templates_x, index = "simpson"),
    shannon_expanded_clones = vegan::diversity(expanded_clones$templates_x, index = "shannon", base = exp(1)),
    invsimpson_expanded_clones = vegan::diversity(expanded_clones$templates_x, index = "invsimpson"),
    fold_change = fold_change, 
    fdr_threshold = fdr_threshold,
    associated_pdf= filename, 
    type = tags[i],
    post = tags2[i],
    pre = tags1[i]) 
  
  packrat[[abr]] = summary_df
  packrat_expanded_clones[[abr]] = expanded_clones
  
  gg = ggplot(dfx, 
              aes(x = productive_frequency_y, y = productive_frequency_x)) + 
    geom_abline( col = "gray", linetype = "dashed") + 
    geom_point(size = .1, alpha = 1) + 
    geom_point( data = focus_greater, shape = 1, size = 2, col = "darkgoldenrod1")  + 
    geom_point( data = focus_less, shape = 1, size = 2, col =  "steelblue")  + 
    scale_y_log10(expand = c(.1,.1)) + 
    scale_x_log10(expand = c(.1,.1)) +
    theme_classic() + 
    annotation_logticks(side = 'lb', size = .2) +
    ylab(tags2[i]) + 
    xlab(tags1[i]) + 
    ggtitle(tags[i])
  
  print(filename)
  print(filepath)
  pdf(filepath, width = 8, height = 8)
  print(gg)
  dev.off()

}
# As we went through the expanded clones exercise, we stored some summary information 
# This table can be used for comparison to functional outputs
summary_information = do.call(rbind, packrat)
#outfile = paste0('/fh/fast/gilbert_p/fg_data/mcelrath_covid/vaccine_samples_vfam_cdr3_vs_emerson_immunerace/figures/summary_info_for_2x_fold_change_FDR_gt_',threshold,'_expanded_clones.tsv')
outfile = paste0(out_dir ,'summary_info_for_2x_fold_change_FDR_gt_',fdr_threshold,'_expanded_clones.tsv')
readr::write_tsv(summary_information, outfile)
# Next, we output the actual exanded clones, which might be useful for finding clustesr
all_expanded_clones = do.call(rbind, packrat_expanded_clones)
#outfile = paste0('/fh/fast/gilbert_p/fg_data/mcelrath_covid/vaccine_samples_vfam_cdr3_vs_emerson_immunerace/figures/expanded_clones_for_2x_fold_change_FDR_gt_',threshold,'_expanded_clones.tsv')
outfile = paste0(out_dir ,'expanded_clones_for_2x_fold_change_FDR_gt_',fdr_threshold,'_expanded_clones.tsv')
readr::write_tsv(all_expanded_clones, outfile)


### END ###



### PRIOR INPUTS ###
# REMOVED FROM THE PRIOR PTID VERSION OF THIS SCRIPT
# This block finds expanded clones and makes plots illustrating them. 
# This dataframe lists the files that were created by outer joins of pre and post files
# df = readr::read_tsv('/fh/fast/gilbert_p/fg_data/mcelrath_covid/vaccine_samples_vfam_cdr3_vs_emerson_immunerace/control/2021_11_28_control_df_outerjoins.tsv')
# base_dir = '/fh/fast/gilbert_p/fg_data/mcelrath_covid/vaccine_samples_vfam_cdr3_vs_emerson_immunerace'
# out_dir = '/fh/fast/gilbert_p/fg_data/mcelrath_covid/vaccine_samples_vfam_cdr3_vs_emerson_immunerace/figures'
#tags1 = stringr::str_extract(df$f1, pattern = "[0-9]{5}_v[0-9]{1,3}")
#tags2 = stringr::str_extract(df$f2, pattern = "[0-9]{5}_v[0-9]{1,3}")

